# Generated by Django 2.2.24 on 2022-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220504_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.NullBooleanField(default=False, verbose_name='Новостройка'),
        ),
    ]
