# Generated by Django 2.2.24 on 2022-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20220504_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=False, null=True, verbose_name='Новостройка'),
        ),
    ]
