# Generated by Django 2.2.24 on 2022-05-04 17:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0008_auto_20220504_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disliker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('disliker', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete='CASCADE', to='property.Flat')),
            ],
        ),
    ]
