# Generated by Django 2.2.24 on 2022-05-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220505_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber_normalized',
            new_name='phonenumber_normalized',
        ),
    ]
