# Generated by Django 2.2.24 on 2022-05-05 17:42
from phonenumbers import parse, is_valid_number, is_valid_number_for_region
from django.db import migrations


def transfer_owners(apps, schema_editor):

    Flat = apps.get_model('property.Flat')
    Owner = apps.get_model('property.Owner')

    for flat in Flat.objects.all():
        phonenumber = parse(flat.owners_phonenumber, 'RU')
        flat.owners_phonenumber_normalized = (
            phonenumber
            if is_valid_number_for_region(phonenumber, 'RU')
            else None
        )

        Owner.objects.get_or_create(
            fullname=flat.owner,
            phonenumber=flat.owners_phonenumber,
            phonenumber_normalized=flat.owners_phonenumber_normalized,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0019_auto_20220505_2041'),
    ]

    operations = [
        migrations.RunPython(transfer_owners),
    ]
