# Generated by Django 2.2.24 on 2022-05-05 19:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20220505_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber_normalized',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер владельца (нормализованный)'),
        ),
    ]
