# Generated by Django 2.2.24 on 2022-05-05 19:46

from django.db import migrations


def link_flats_with_owners(apps, schema_editor):
    Flat = apps.get_model('property.Flat')
    Owner = apps.get_model('property.Owner')

    for flat in Flat.objects.all():
        updated_owner = Owner.objects.filter(fullname=flat.owner)[0]
        updated_owner.flats.add(flat)
        updated_owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20220505_2233'),
    ]

    operations = [
        migrations.RunPython(link_flats_with_owners),
    ]
