# Generated by Django 2.2.24 on 2022-05-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20220505_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber_normalized',
        ),
    ]
